### * List of courses - OK - *
GET http://localhost:3000/api/courses


### * Couse by id - OK - 
GET http://localhost:3000/api/courses/658ec1ec43fea95f9acfa75a


### * Create a new course - OK - *
POST http://localhost:3000/api/courses
Content-Type: application/json

{
  "name": "",
  "price": 25000,
  "description": "prueba error interno 5"
}


### * Update course by id - OK - *
PATCH http://localhost:3000/api/courses/658ec1ec43fea95f9acfa75a
Content-Type: application/json

{
  "name": "Otra prueba 2",
  "price": "",
  "description":""
}


### * Delete course by id - OK - *
DELETE http://localhost:3000/api/courses/65898b2a01ae93b55e198c03
